name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and pull the Docker image
      run: docker build --pull . -t ubi8-nginx:latest

    
